<div id="headbar"></div>
<div>
	<ul>
		<li>
			<a href="../">
				<p class="p"><img src="<?=Icon::get_parent('large')?>" alt="" /></p>
				<p class="n">..</p>
				<p class="i"><?=$lang->parent_dir?></p>
			</a>
		</li><? $n = 1; foreach ($dlist->list as $key => $item): $info = ($item['type'] == 'file') ? $item[$config->tpl_file_info] : $item[$config->tpl_folder_info] ; $thumbnail = (Icon::is_image($item['ext']) && $config->thumbnails) ? ", '".Icon::get_thumbnail_url($item['name'], $config->tpl_preview_width, $config->tpl_preview_height)."'" : '' ; ?>
		<li>
			<a href="<?=rawurlencode($item['name'])?><? if($item['type'] == 'dir') echo '/'; ?>" onmouseover="iP(<?=$n.$thumbnail?>)" onmouseout="o()">
				<span id="p<?=$n?>"><div class="name"><?=$item['name']?></div>
<?
	if ( !empty($fields['size']) && $item['type'] == 'file' ) echo $lang->size.': '.$item['size'].' ('.number_format($item['size_raw']).' bytes)<br />';
	if ( !empty($fields['mtime']) && $item['type'] == 'file' ) echo $lang->mtime.': '.$item['mtime'].'<br />';
	if ( !empty($fields['atime']) ) echo $lang->atime.': '.$item['atime'].'<br />';
	if ( !empty($fields['perms']) ) echo $lang->perms.': '.$item['perms'].'<br />';
	if ( !empty($fields['chmod']) ) echo $lang->chmod.': '.$item['chmod'].'<br />';
	if ( !empty($fields['owner']) ) echo $lang->owner.': '.$item['owner'].'<br />';
	if ( !empty($fields['group']) ) echo $lang->group.': '.$item['group'].'<br />';
	if ( !empty($fields['owner_id']) ) echo $lang->owner_id.': '.$item['owner_id'].'<br />';
	if ( !empty($fields['group_id']) ) echo $lang->group_id.': '.$item['group_id'].'<br />';
?>
				</span>
				<p class="p"><img src="<?=Icon::get_url($item['name'], 'large', $item['type'], true)?>" alt="" /></p>
				<p class="n"><?=Path::breakFilename($item['name'], $config->tpl_file_maxlength, $config->tpl_wordbreak)?></p>
				<p class="i"><?=$info?></p>
			</a>
		</li><? $n++; endforeach; ?>
	</ul>
</div>
