<table border="0" cellspacing="0" cellpadding="0" id="tiles"><tr><td>
<div id="sort-nav">
	<a href="<?=Sort::get_url('name')?>"><?=$lang->name?></a> | <a href="<?=Sort::get_url('size')?>"><?=$lang->size?></a> | <a href="<?=Sort::get_url('mtime')?>"><?=$lang->mtime?></a>
</div>
<ul>
	<? if ( !$is_root ): ?>
	<li><a href="../"><img src="<?=Icon::get_parent('large')?>" alt="" align="left" />
		<span class="name">..</span><span class="info"><?=$lang->parent_dir?></span></a></li>
	<? endif ?>
	<? foreach ($dlist->list as $key => $item): $info = ($item['type'] == 'file') ? $item['size'] : $item['mtime'] ;?>
	<li><a href="<?=DIR_URL.$item['name']?><? if($item['type'] == 'dir') echo '/'; ?>"><img src="<?=Icon::get_url($item['ext'], 'large', $item['type'])?>" alt="" align="left" />
		<span class="name"><?=$item['name']?></span><span class="info"><?=$info?></span></a></li>
	<? endforeach ?>
</ul>	
</td></tr></table>