<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
		<title>Index of <?= DIR_URL ?></title>
		<style type="text/css" media="screen">
		/* <![CDATA[ */
		
			<? include(TPL_PATH.'stylesheets/media.css') ?>
			
		/* ]]> */
		</style>
		
	</head>
	<body id="index">
		<table border="0" cellspacing="1" cellpadding="3" id="list">
			<tr>
				<th></th>
				<th>Name</th>
				<th>Size</th>
				<th>Date Modified</th>
				<th>Permissions</th>
				<th>Owner</th>
			</tr>
			<? if (!empty($dlist->parent) || $dlist->parent != '/'): $parent = $dlist->parent; ?>
			<tr>
				<td><img src="<?=icons_get_parent('large')?>" class="" alt="" /></td>
				<td><a href="../"><?=$parent['name']?></a></td>
				<td><?=$parent['size']?></td>
				<td><?=$parent['mtime']?></td>
				<td><?=$parent['perms']?></td>
				<td><?=$parent['owner']?></td>
			</tr>
			<? endif ?>
			<? foreach ($dlist->list as $key => $item): ?>
			<tr>
				<td><img src="<?=icons_get_url($item['ext'], 'large', $item['type'])?>" class="" alt="" /></td>
				<td><a href="<?=DIR_URL.$item['name']?><? if($item['type'] == 'dir') echo '/'; ?>"><?=$item['name']?></a></td>
				<td><?=$item['size']?></td>
				<td><?=$item['mtime']?></td>
				<td><?=$item['perms']?></td>
				<td><?=$item['owner']?></td>
			</tr>
			<? endforeach ?>
		</table>
		<div id="stats">
			Page generated in <?=$timer->end()?> seconds.
		</div>
	</body>
</html>