<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
		<title>Index of <?=DIR_URL?></title>
		<style type="text/css" media="screen">
		/* <![CDATA[ */
<? include(TPL_PATH.'stylesheets/screen.css') ?>
		/* ]]> */
		</style>
	</head>
	<body id="index">
		<div id="header">
			Index of <?=DIR_URL?>
		</div>
		<table border="0" cellspacing="1" cellpadding="0" id="list">
			<tr>
				<th class="icon"></th>
				<th class="name">Name</th>
				<th class="size">Size</th>
				<th class="mtime">Date Modified</th>
				<th class="perms">Permissions</th>
				<th class="owner">Owner</th>
			</tr>
			<? if (!empty($parent['name']) || $parent['name'] != '/'): ?>
			<tr>
				<td class="icon"><a href="../" title="Parent Directory"><img src="<?=Icon::get_parent($config->tpl_icon_size)?>" class="" alt="" /></a></td>
				<td class="name"><a href="../" title="Parent Directory">..</a></td>
				<td class="size"><?=$parent['size']?></td>
				<td class="mtime"><?=$parent['mtime']?></td>
				<td class="perms"><?=$parent['perms']?></td>
				<td class="owner"><?=$parent['owner']?></td>
			</tr>
			<? endif ?>
			<? foreach ($dlist->list as $key => $item): ?>
			<tr>
				<td class="icon">
					<a href="<?=DIR_URL.$item['name']?><? if($item['type'] == 'dir') echo '/'; ?>" title="<?=$item['name']?>">
						<img src="<?=Icon::get_url($item['ext'], $config->tpl_icon_size, $item['type'])?>" class="" alt="" />
					</a>
				</td>
				<td class="name"><a href="<?=DIR_URL.$item['name']?><? if($item['type'] == 'dir') echo '/'; ?>"><?=$item['name']?></a></td>
				<td class="size"><?=$item['size']?></td>
				<td class="mtime"><?=$item['mtime']?></td>
				<td class="perms"><?=$item['perms']?></td>
				<td class="owner"><?=$item['owner']?></td>
			</tr>
			<? endforeach ?>
		</table>
		<div id="stats">
			Page generated in <?=$timer->end()?> seconds.
		</div>
	</body>
</html>