<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
		<title><?=$lang->index_of.' '.DIR_URL?></title>
		<script src="<?=TPL_URL?>javascripts/main.js" type="text/javascript" language="javascript" charset="utf-8"></script>
		<style type="text/css" media="screen">
		/* <![CDATA[ */
<? include(TPL_PATH.'stylesheets/screen.css') ?>
		/* ]]> */
		</style>
	</head>
	<body id="index">
		<div id="header">
			<?=$lang->index_of.' '.DIR_URL?>
		</div>
		<div id="view-nav">
			<a href="javascript:;" onclick="set_view('icons')">Icons</a> | <a href="javascript:;" onclick="set_view('tiles')">Tiles</a> | <a href="javascript:;" onclick="set_view('details')">Details</a>
		</div>
		<div id="server-info"><?=SERVER_INFO?></div>
		<div id="files">
<? include(TPL_PATH.$config->tpl_mode) ?>
		</div>
		<div id="stats">
			<div id="timer">Powered by dList. <?=$timer->end()?>.</div>
		</div>
	</body>
</html>